DROP TABLE IF EXISTS Observation CASCADE;
DROP TABLE IF EXISTS SpaceShipCharacteristic CASCADE;
DROP TABLE IF EXISTS SpaceObjectCharacteristic CASCADE;
DROP TABLE IF EXISTS ObservationTarget CASCADE;
DROP TABLE IF EXISTS Characteristic CASCADE;
DROP TABLE IF EXISTS SpaceShip CASCADE;
DROP TABLE IF EXISTS SpaceObject CASCADE;
DROP TABLE IF EXISTS Observer CASCADE;
DROP TABLE IF EXISTS Route CASCADE;
DROP TABLE IF EXISTS EventType CASCADE;

DROP TYPE IF EXISTS TARGET_TYPE_ENUM CASCADE;
DROP TYPE IF EXISTS ENGINE_TYPE_ENUM CASCADE;
DROP TYPE IF EXISTS OBJECT_TYPE_ENUM CASCADE;
DROP TYPE IF EXISTS POINT_COORDINATES CASCADE;